### ISSUE TITLE
PostBuild hook generates an illegal filename

### ISSUE THREAD

**Issue by KonajuGames** [Protobuild/Protobuild#163] opened 2016-02-29 14:35 UTC
The timestamp filename generated as part of the post-build hook uses %(FullPath), which expands to an absolute path.  When building iOS projects from Visual Studio, this Windows absolute path is used as a path on the Mac.  The path contains a colon, which prevents the file from working on the Mac, and thus the build fails.

```
1>D:\Git\MonoGame\ThirdParty\Lidgren.Network\Lidgren.Network.iOS.csproj(195,5): error : Could not find a part of the path "/Users/slygamer/Library/Caches/Xamarin/mtbs/builds/LidgrenNetworkiOS/622e37883a5e37846901049cf7a34b4e/D:/Git/MonoGame/ThirdParty/Lidgren.Network/obj/iOS/iPhoneSimulator/Debug/Lidgren.Network.dll.timestamp". at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x1a03910 + 0x0021d> in <filename unknown>:0
```

Firstly, what is this timestamp used for?  I couldn't see a purpose for it.

For target platform iOS or tvOS and host platform Windows, do not use the full path.  Just use the `TargetFileName` instead.  Xamarin provides the path to its build directory on the Mac build machine.

**Comment by hach-que** [comment] 2016-02-29 14:41
Is this on the latest Protobuild?

**Comment by hach-que** [comment] 2016-02-29 14:41
(I ask because there's already explicitly logic around handling iOS / tvOS on Windows: https://github.com/Protobuild/Protobuild/blob/master/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L2391)

**Comment by KonajuGames** [comment] 2016-02-29 14:47
I saw that logic in the xlst I extracted from MonoGame's Protobuild version.  I just re-generated the project files again.  This is what we get in the iOS project files on Windows.

```
  <PropertyGroup>
    <_PostBuildHookTimestamp>@(IntermediateAssembly-&gt;'%(FullPath).timestamp')</_PostBuildHookTimestamp>
  </PropertyGroup>
  <Target Name="PostBuildHooks" Inputs="@(IntermediateAssembly);@(ReferencePath)" Outputs="@(IntermediateAssembly);$(_PostBuildHookTimestamp)" AfterTargets="CoreCompile" BeforeTargets="AfterCompile">
    <Touch Files="$(_PostBuildHookTimestamp)" AlwaysCreate="True" SessionId="$(BuildSessionId)" />
  </Target>
```

This means the test is failing and it is using the `otherwise` clause.

What is this timestamp for?  What does it do?

**Comment by hach-que** [comment] 2016-02-29 14:52
The timestamp is used so that we don't cause projects to always be rebuilt when the source files haven't changed.  Because post-build hooks may modify the intermediate assembly in-place, we don't want to trigger a rebuild of the project unnecessarily, and the timestamp file is used to make sure MSBuild exhibits the correct behaviour.

In your XSLT files near that conditional, can you add:

```
<info>
  <target><xsl:value-of select="$root/Input/Generation/Platform" /></target>
  <host><xsl:value-of select="$root/Input/Generation/HostPlatform" /></host>
  <xsl:if test="($root/Input/Generation/Platform = 'iOS' or $root/Input/Generation/Platform = 'tvOS') and $root/Input/Generation/HostPlatform = 'Windows'">
    <testfullypasses />
  </xsl:if>
  <xsl:if test="$root/Input/Generation/HostPlatform = 'Windows'">
    <testhostpasses />
  </xsl:if>
  <xsl:if test="($root/Input/Generation/Platform = 'iOS' or $root/Input/Generation/Platform = 'tvOS')">
    <testtargetpasses />
  </xsl:if>
</info>
```

and then re-generate the projects.

**Comment by hach-que** [comment] 2016-02-29 14:57
(Put that block immediately before the `<Target Name="PostBuildHooks" Inputs="@(IntermediateAssembly);@(ReferencePath)" ...` line)

**Comment by KonajuGames** [comment] 2016-02-29 14:58
Now I see the subtle difference between our version of Protobuild and yours.

Ours
```
        <Touch Files="$(_PostBuildHookTimestamp)" AlwaysCreate="True">
          <xsl:if test="($root/Input/Generation/Platform = 'iOS' or $root/Input/Generation/Platform = 'tvOS') and $root/Input/Generation/HostPlatform = 'Windows'">
            <xsl:attribute name="SessionId">
              <xsl:text>$(BuildSessionId)</xsl:text>
            </xsl:attribute> 
          </xsl:if>
        </Touch>
```

Yours
```
        <xsl:choose>
          <!-- We can't use the <Touch> task, because Xamarin iOS remaps it on Windows to be a remote command -->
          <xsl:when test="($root/Input/Generation/Platform = 'iOS' or $root/Input/Generation/Platform = 'tvOS') and $root/Input/Generation/HostPlatform = 'Windows'">
            <LocalTouch Path="$(_PostBuildHookTimestamp)" />
          </xsl:when>
          <xsl:otherwise>
            <Touch Files="$(_PostBuildHookTimestamp)" AlwaysCreate="True" />
          </xsl:otherwise>
        </xsl:choose>
```

**Comment by KonajuGames** [comment] 2016-02-29 14:58
Ours must be an older version.

**Comment by hach-que** [comment] 2016-02-29 14:59
Ah yes, there was a bug-fix around this a while back because of Xamarin nonsense (they changed the way the build targets on iOS on Windows behaved).  Upgrading to the latest version of Protobuild should fix the issue.

**Comment by hach-que** [comment] 2016-02-29 15:00
Going to close this off unless the issue is reproducible on the latest version.

**Closed by hach-que** 2016-02-29 15:00 UTC

**Comment by tomspilman** [comment] 2016-06-18 06:12
Uggh...  I got bit by this bug again... kept me from building iOS for 2 days now.  The MonoGame version of Protobuild is generating this:

```
  <PropertyGroup>
    <_PostBuildHookTimestamp>@(IntermediateAssembly-&gt;'%(FullPath).timestamp')</_PostBuildHookTimestamp>
  </PropertyGroup>
  <Target Name="PostBuildHooks" Inputs="@(IntermediateAssembly);@(ReferencePath)" Outputs="@(IntermediateAssembly);$(_PostBuildHookTimestamp)" AfterTargets="CoreCompile" BeforeTargets="AfterCompile">
    <Touch Files="$(_PostBuildHookTimestamp)" AlwaysCreate="True" SessionId="$(BuildSessionId)" />
  </Target>
```
Which at least for me failed to build from Visual Studio remotely on the Mac.

I'm working on a PR now to update Protobuild in the MonoGame repo with a good version.

**Comment by hach-que** [comment] 2016-06-18 06:31
Oh, I assumed that someone would have already sent a PR to update Protobuild after this issue was initially resolved.

**Comment by tomspilman** [comment] 2016-06-18 06:33
Looks like It just got forgotten.
